name: Airis
options:
  bundleIdPrefix: com.wangnov
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: Airis
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 3VT538F8B6

packages:
  ArgumentParser:
    url: https://github.com/apple/swift-argument-parser
    from: "1.3.0"

targets:
  Airis:
    type: application
    platform: macOS
    sources:
      - path: Sources/AirisCore
      - path: Sources/Airis
      - path: Sources/Airis/Assets.xcassets
    info:
      path: Sources/Airis/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: Airis
        CFBundleDisplayName: Airis
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleVersion: "1.0.0"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        LSMinimumSystemVersion: "14.0"
        # CLI App - 无 GUI
        LSUIElement: true
        LSBackgroundOnly: true
    dependencies:
      - package: ArgumentParser
        product: ArgumentParser
    entitlements:
      path: Airis.entitlements
      properties:
        com.apple.developer.sensitivecontentanalysis.client:
          - analysis
    settings:
      base:
        PRODUCT_NAME: Airis
        PRODUCT_MODULE_NAME: Airis
        PRODUCT_BUNDLE_IDENTIFIER: com.wangnov.airis
        SWIFT_STRICT_CONCURRENCY: complete
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: XCODE_BUILD
        DEVELOPMENT_TEAM: 3VT538F8B6
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Airis.entitlements
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
        # App Wrapper 设置
        INFOPLIST_FILE: Sources/Airis/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # 禁用不需要的 App 功能
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"

  AirisTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/AirisTests
        excludes:
          - "Resources/*.swift"
      - path: Sources/AirisCore
    dependencies:
      - package: ArgumentParser
        product: ArgumentParser
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_MODULE_NAME: AirisTests
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: XCODE_BUILD

schemes:
  Airis:
    build:
      targets:
        Airis: all
        AirisTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AirisTests
    archive:
      config: Release
